export const PREFIX = "@@auth/";

export const ASYNC_AUTH_INIT = `${PREFIX}ASYNC_AUTH_INIT`;
export const HANDLE_NOTIFICATION = `${PREFIX}HANDLE_NOTIFICATION`;

export const AUTH_SIGN_UP_SUCCESS = `${PREFIX}AUTH_SIGN_UP_SUCCESS`;
export const AUTH_SIGN_IN_SUCCESS = `${PREFIX}AUTH_SIGN_IN_SUCCESS`;
export const AUTH_SIGN_OUT_SUCCESS = `${PREFIX}AUTH_SIGN_OUT_SUCCESS`;
export const AUTH_AUTHENTICATION_FAILURE = `${PREFIX}AUTH_AUTHENTICATION_FAILURE`;
export const GET_INVITED_USER_INFO_SUCCESS = `${PREFIX}GET_INVITED_USER_INFO_SUCCESS`;
export const PASSWORD_RESET_SUCCESS = `${PREFIX}PASSWORD_RESET_SUCCESS`;
export const RESET_PASSWORD_EMAIL_SENT_SUCCESS = `${PREFIX}RESET_PASSWORD_EMAIL_SENT_SUCCESS`;