export const PREFIX = "@@customerReturn/";

export const ASYNC_CUSTOMER_RETURN_INIT = `${PREFIX}ASYNC_CUSTOMER_RETURN_INIT`;
export const HANDLE_NOTIFICATION = `${PREFIX}HANDLE_NOTIFICATION`;

export const GET_CUSTOMER_RETURN_SUCCESS = `${PREFIX}GET_CUSTOMER_RETURN_SUCCESS`;
