export const PREFIX = "@@supplier/";

export const ASYNC_SUPPLIER_INIT = `${PREFIX}ASYNC_SUPPLIER_INIT`;
export const HANDLE_NOTIFICATION = `${PREFIX}HANDLE_NOTIFICATION`;

export const GET_SUPPLIERS_SUCCESS = `${PREFIX}GET_SUPPLIERS_SUCCESS`;
